bookers2-main/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'

  resources :books, only: [:index, :create, :edit, :update, :show, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update]

end

bookers2-main/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers2-main/app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

bookers2-main/app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

bookers2-main/app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id

end

bookers2-main/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  # name: 一意性 & 2~20文字
  validates :name, uniqueness: true, length: {in: 2..20}
  # introduction: 最大50文字
  validates :introduction, length: { maximum: 50}

  has_one_attached :profile_image

  def get_profile_image(height, width)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [height, width]).processed
  end

end

bookers2-main/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about, :sign_up, :sign_in]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

bookers2-main/app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    BookComment.find(params[:id]).destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

bookers2-main/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @books = Book.all
    @user = @book.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    @user = @book.user
    if @user.id != current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :edit
    end
  end

  # 投稿データの保存
  def create
    @user = current_user
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def destroy
    book = Book.find(params[:id]) # データの取得(idを用いて1件ずつ)
    if book.destroy # データの削除
      flash[:notice] = "Book was successfully destroyed."
      redirect_to books_path
    else
      render :index
    end
  end


  # 投稿データのストロングパラメータ
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end


end

bookers2-main/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end

end

bookers2-main/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

bookers2-main/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def index
    id = current_user.id
    @user = User.find(id)
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

bookers2-main/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers2-main/app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

bookers2-main/app/helpers/books_helper.rb
module BooksHelper
end

bookers2-main/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bookers2-main/app/helpers/homes_helper.rb
module HomesHelper
end

bookers2-main/app/helpers/users_helper.rb
module UsersHelper
end

bookers2-main/app/views/books/_form.html.erb
<!-- 投稿フォーム -->
<h2 class="mt-3">New book</h2>
<%= form_with model: book do |f| %>
  <div class="form-group">
    <label for="book_title">title</label>
    <%= f.text_field :title, class:"form-control book_title" %>
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body, class:"form-control book_body" %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class:"btn btn-success" %>
  </div>
<% end %>

bookers2-main/app/views/books/edit.html.erb
<p id="notice"><%= flash[:notice] %></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= form_with model: @book do |f| %>
      <!-- エラー -->
        <div id="error_explanation">
          <% if @book.errors.any? %>
            <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
              <ul>
                <% @book.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            <% end %>
        </div>


        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class:"form-control book_title", id:"book_title"%>
        </div>

        <div class="form-group">
          <label for="book_body">Opinion</label>
          <%= f.text_area :body, class:"form-control book_body", id:"book_Body"%>
        </div>

        <div class="form-group">
          <%= f.submit "Update Book", class:"btn btn-success" %>
        </div>
      <% end %>

      <%= link_to "Show", book_path, class:"book_#{@book.id}" %>
      |
      <%= link_to "Back", books_path, class:"back" %>

    </div>
  </div>
</div>

bookers2-main/app/views/books/index.html.erb
<!-- books/index -->
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div id="error_explanation">
    <% if @book.errors.any? %>
      <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
  </div>

  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
      <%= render 'form', book: @book %>
    </div>


    <!-- みんなが投稿した本の一覧表示 -->
    <div class="col-md-8 offset-md-1">
      <!-- 投稿した本の一覧表示 -->
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead> <!-- 水平方向の表 -->
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="5"></th> <!-- セルを3つ結合 -->
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to(user_path(book.user_id)) do %>
                  <%= image_tag book.user.get_profile_image(50,50) %>
                <% end %>
              </td>
              <td>
                <%= link_to(book_path(book.id), class:"book_#{book.id}") do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>

              <% if book.favorited_by?(current_user) %>
                <td>
                  <%= link_to book_favorites_path(book), method: :delete, class:"red-heart" do %>
                    <i class="fas fa-heart"></i><%= book.favorites.count %>
                  <% end %>
                </td>
              <% else %>
                <td>
                  <%= link_to book_favorites_path(book), method: :post, class:"blue-heart" do %>
                    <i class="fas fa-heart"></i><%= book.favorites.count %>
                  <% end %>
                </td>
              <% end %>
              <td><%= "コメント数: #{book.book_comments.count}" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

bookers2-main/app/views/books/show.html.erb
<p id="notice"><%= flash[:notice] %></p>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <!-- 部分テンプレート呼び出す -->
      <%= render 'users/info', {user: @user, book: @book} %>
      <%= render 'form', book: @book_new %>
    </div>

    <div class="col-md-8 offset-md-1">
      <!-- 投稿した本の一覧表示 -->
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">

        <tbody>

          <tr>
            <td>
              <%= link_to(user_path(@book.user_id)) do %>
                <%= image_tag @user.get_profile_image(30,30) %><br>
                <%= @user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to(book_path(@book.id)) do %>
                <%= @book.title %>
              <% end %>
            </td>
            <td><%= @book.body %></td>
            <% if @user == current_user %>
              <td><%= link_to 'Edit', edit_book_path(@book.id), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
              <td><%= link_to 'Destroy', book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？", class: "btn btn-sm btn-danger destroy_book_#{@book.id}" %></td>
            <% end %>

            <% if @book.favorited_by?(current_user) %>
              <td>
                <%= link_to book_favorites_path(@book), method: :delete, class:"red-heart" do %>
                  <i class="fas fa-heart"></i><%= @book.favorites.count %>
                <% end %>
              </td>
            <% else %>
              <td>
                <%= link_to book_favorites_path(@book), method: :post, class:"blue-heart" do %>
                  <i class="fas fa-heart"></i><%= @book.favorites.count %>
                <% end %>
              </td>
            <% end %>
            <td>コメント数: <%= @book.book_comments.count %></td>
          </tr>

        </tbody>
      </table>

      <div>
        <% @book.book_comments.each do |book_comment| %>
          <div>
            <%= image_tag book_comment.user.get_profile_image(50,50) %>
            <%= book_comment.user.name %>
            <%= book_comment.comment %>
            <% if book_comment.user == current_user %>
              <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, "data-confirm" => "本当に消しますか？", class: "btn btn-sm btn-danger destroy_book_#{@book.id}" %>
            <% end %>
          </div>
        <% end %>
      </div>

      <div>
        <%= form_with model: [@book, @book_comment] do |f| %>
          <p>test</p>
          <%= f.text_area :comment, rows: '4', class:"form-control comment" %>
          <%= f.submit "送信" %>
        <% end %>
      </div>

    </div>
  </div>
</div>

bookers2-main/app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>!
    </h1>
  </div>
</div>

bookers2-main/app/views/homes/top.html.erb
<p id="notice"><%= flash[:notice] %></p>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>
        welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        !!
      </h1>

      <p>
        In
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        ,
      </p>

      <p>you can share and exchange your opinions , inpressions , and emotions</P>

      <p>about various books!</p>

      <div class="btn-wrapper col-10 mx-auto">
        <div calss="row">
          <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div calss="row">
          <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>


    </div>
  </div>
</div>

bookers2-main/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to(root_path, class:"navbar-brand") do %>
            <span>Bookers</span>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <!-- ログイン中 -->
              <li>
                <%= link_to(user_path(current_user.id), class:"nav-link text-light") do %>
                  <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li class="nav-item" >
                <%= link_to(users_path, class:"nav-link text-light") do %>
                  <i class="fas fa-users"></i> Users
                <% end %>
              </li>
              <li class="nav-item" >
                <%= link_to(books_path, class:"nav-link text-light") do %>
                  <i class="fas fa-book-open"></i> Books
                <% end %>
              </li>
              <li>
                <%= link_to(destroy_user_session_path, method: :delete, class:"nav-link text-light") do %>
                  <i class="fas fa-sign-out-alt"></i> logout
                <% end %>
              </li>
            <% else %>
              <!-- ログアウト中 -->
              <li class="nav-item" >
                <%= link_to(root_path, class:"nav-link text-light") do %>
                <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li class="nav-item" >
                <%= link_to(about_path, class:"nav-link text-light") do %>
                <i class="fas fa-link"></i> About
                <% end %>
              </li>
              <li class="nav-item" >
                <%= link_to(new_user_registration_path, class:"nav-link text-light") do %>
                <i class="fas fa-user-plus"></i> sign up
                <% end %>
              </li>
              <li class="nav-item" >
                <%= link_to(new_user_session_path, class:"nav-link text-light") do %>
                <i class="fas fa-sign-in-alt"></i> login
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>

bookers2-main/app/views/users/_info.html.erb
<!-- 部分テンプレートファイル -->
<h2>User info</h2>
<%= image_tag user.get_profile_image(100,100) %>
<table class="table">
  <tbody>
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>

<div class="row">
  <%= link_to(edit_user_path(user.id), class:"btn btn-outline-secondary btn-block edit_user_#{user.id}") do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

bookers2-main/app/views/users/edit.html.erb
<p id="notice"><%= flash[:notice] %></p>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <h2>User info</h2>
      <%= form_with model: @user do |f| %>
        <!-- エラー -->
        <div id="error_explanation">
          <% if @user.errors.any? %>
            <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
              <ul>
                <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            <% end %>
        </div>

        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name, class:"form-control name", id:"user_name" %>
        </div>

        <div class="form-group">
          <label for="user_image">Image</label>
          <%= f.file_field :profile_image, class:"form-control-file user_image", id:"user_profile_image", accept: "image/*" %>
        </div>

        <div class="form-group">
          <label for="user_introduction">Introduction</label>
          <%= f.text_area :introduction, class:"form-control introduction", id:"user_introduction" %>
        </div>

        <div class="form-group">
          <%= f.submit "Update User", class:"btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

bookers2-main/app/views/users/index.html.erb
<!-- サクセスメッセージ -->
<p id="notice"><%= flash[:notice] %></p>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <!-- 部分テンプレート呼び出す -->
      <%= render 'users/info', user: @user %>
      <%= render 'books/form', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
        <thead> <!-- 水平方向の表 -->
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th> <!-- セルを3つ結合 -->
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_profile_image(100,100) %></td>
              <td><%= user.name %></td>
              <td>
                <%= link_to(user_path(user.id)) do %>
                  Show
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

bookers2-main/app/views/users/show.html.erb
<!-- サクセスメッセージ -->

<p id="notice"><%= flash[:notice] %></p>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <!-- user_infoのテンプレート呼び出す -->
      <%= render 'info', user: @user %>

      <%= render 'books/form', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <!-- 投稿した本の一覧表示 -->
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead> <!-- 水平方向の表 -->
          <tr>
            <th></th>
            <th>Title</th>
            <th>body</th>
            <th colspan="3"></th> <!-- セルを3つ結合 -->
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to(user_path(book.user_id)) do %>
                  <%= image_tag book.user.get_profile_image(100,100) %>
                <% end %>
              </td>
              <td>
                <%= link_to(book_path(book.id)) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
              <% if book.favorited_by?(current_user) %>
                <td>
                  <%= link_to book_favorites_path(book), method: :delete, class:"red-heart" do %>
                    <i class="fas fa-heart"></i><%= book.favorites.count %>
                  <% end %>
                </td>
              <% else %>
                <td>
                  <%= link_to book_favorites_path(book), method: :post, class:"blue-heart" do %>
                    <i class="fas fa-heart"></i><%= book.favorites.count %>
                  <% end %>
                </td>
              <% end %>
              <td><%= "コメント数: #{book.book_comments.count}" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>