bookers1-main/config/routes.rb
Rails.application.routes.draw do
  get '/' => 'homes#top', as: 'root' # top
  get 'books' => 'books#index' # Books
  post 'books' => 'books#create' # createに移行
  get 'books/:id' => 'books#show', as: 'book' # show
  get 'books/:id/edit' => 'books#edit', as: 'edit_book' # edit
  patch 'books/:id' => 'books#update', as: 'update' # update
  delete 'books/:id' => 'books#destroy', as: 'destory_book' # destroy
end

bookers1-main/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers1-main/app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

bookers1-main/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

bookers1-main/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id]) # データの取得(idを用いて1件ずつ)
    if book.destroy # データの削除
      flash[:notice] = "Book was successfully destroyed."
      redirect_to books_path
    else
      render :index
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

bookers1-main/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

bookers1-main/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers1-main/app/helpers/books_helper.rb
module BooksHelper
end

bookers1-main/app/helpers/homes_helper.rb
module HomesHelper
end

bookers1-main/app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
    <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message%></li>
    <%end%>
    </ul>
  </div>

<% end %>

<!-- form_with部分 -->
<%= form_with model: @book, url: update_path(@book.id), method: :patch do |f| %>
<% if @book.errors.any? %>
  <%= f.label :title, "Title" %>
<% else %>
  Title<br>
<% end %>
  <div class=field><%= f.text_field :title %></div>

<% if @book.errors.any? %>
  <%= f.label :body, "Body" %>
<% else %>
  Body<br>
<% end %>
  <div class=field><%= f.text_area :body %></div>

  <div class=actions><%= f.submit 'Update Book' %></div>
<% end %>

<%= link_to 'Show', book_path(@book.id) %>
|
<%= link_to 'Back', books_path %>

bookers1-main/app/views/books/index.html.erb
<% if flash[:notice] %>
  <p id="notice"><%= flash[:notice] %></p>
<% end %>

<h1>Books</h1>
<!-- table部分 -->
<table>
  <thead> <!-- 水平方向の表 -->
    <tr>
      <th>Title</th>
      <th>body</th>
      <th colspan="3"></th> <!-- セルを3つ結合 -->
    </tr>
  </thead>


  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to 'Show', book_path(book.id), class: "show_#{book.id}" %></td>
        <td><%= link_to 'Edit', edit_book_path(book.id), class: "edit_#{book.id}" %></td>
        <td><%= link_to 'Destroy', destory_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?", class: "destory_#{book.id}" %></td>
      </tr>
    <% end %>


  </tbody>
</table>


<h2>New book</h2>
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
    <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message%></li>
    <%end%>
    </ul>
  </div>
<% end %>
<!-- form_with部分 -->
<%= form_with model: @book do |f| %>
  
  <div class=field><%= f.text_field :title %></div>

  <%= f.label :body, "Body" %>
  <div class=field><%= f.text_area :body %></div>

  <div class=actions><%= f.submit 'Create Book' %></div>
<% end %>

bookers1-main/app/views/books/show.html.erb
<% if flash[:notice] %>
  <p id="notice"><%= flash[:notice] %></p>
<% end %>

<p><strong>Title:</strong><%= @book.title %></p>

<p><strong>Body:</strong><%= @book.body %></p>


<%= link_to 'Edit', edit_book_path(@book.id) %>
|
<%= link_to 'Back', books_path %>

bookers1-main/app/views/homes/top.html.erb
<h1>ようこそ Bookersへ！</h1>
<p><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>
<p><%= link_to 'start', books_path %></p>

bookers1-main/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>